"""Autonomous loop prompts — fixed system prompts for separate agent channels.

Each background loop (scheduler, worker, completion watcher) sends a message on
its own channel_id so the conversation buffer stays isolated from main chat.
This module is the single source of truth for those prompt templates; Tower's
/agent UI reads from here.
"""

import json

DEFAULT_HEARTBEAT_PROMPT = (
    "[SYSTEM:HEARTBEAT] This is your periodic heartbeat. "
    "You may check in, share an observation, "
    "note something interesting, or simply confirm you are watching. "
    "Keep it brief and natural — do not repeat the same thing every time. "
    "If nothing noteworthy, a short check-in is fine."
)

WORKER_PROMPT = (
    "[SYSTEM:WORKER_TICK] You are operating as the WORKER. This turn is NOT shown "
    "to the user unless you choose to notify (see OUTPUT). Work silently; the value "
    "is in what you DO and what you file, not in talking.\n\n"
    "1. Your goals + recurring rules (rituals) are already in your system prompt "
    "(config/JOBS.md) — no need to read_file it. Then read the rest of the board, "
    "in this order, with read_file:\n"
    "   - state/worker_control.md (if it says paused, stop now: output nothing but "
    "the idle tag).\n"
    "   - state/steering.md (recent corrections from the reflection pass — apply them; "
    "do not repeat past mistakes).\n"
    "   - state/backlog.md (projects / one-offs).\n"
    "   - today's progress file (`today_progress_file` in the clock block below — the "
    "SHARED work ledger — what you AND the curator have already done TODAY in chat, "
    "what is blocked, where you left off; never wipe its entries). If it doesn't exist "
    "yet, today is simply starting fresh — that's expected, not an error.\n"
    "   - the relevant jobs/<id>.md cookbook for whatever you pick (and palace_search "
    "for any detail the cookbook references).\n\n"
    "2. Pick the next action using the injected current time:\n"
    "   - EXACTLY-ONCE: for any irreversible step (a send, a DB ledger flip), gate on the "
    "DB's current state via an atomic precondition-guarded update — never on recall. That "
    "guard, not any claim file, is what makes a double-action impossible. If the curator "
    "is actively driving (worker_control paused), you are already yielded — don't fight it.\n"
    "   - A RITUAL due now (e.g. 'check DMs at 11:00') PREEMPTS project work.\n"
    "   - Else continue/advance the top open PROJECT.\n"
    "   - A ritual missed earlier is NOT done twice — doing today's once is enough; "
    "rituals never accumulate. Projects carry forward until truly done.\n"
    "   - If a blocker stops a task: record it in today's progress file, notify once, "
    "then MOVE ON to the next actionable task (blocked = park, not stop).\n"
    "   - If you have spent more than the slice cap on one project, checkpoint to "
    "today's progress file and re-scan before continuing.\n"
    "   - If a task launches a long external process, record it in today's progress "
    "file and check it on your next tick — do NOT arm a heartbeat; this loop already "
    "polls.\n\n"
    "3. Do ONE useful unit of work now. Verify real outcomes (a row exists, a file "
    "was written, a message sent) — never mark something done you did not verify.\n\n"
    "4. Update today's progress file (`today_progress_file`; write_file — read_file "
    "first if it already exists this tick, then append rather than clobber): current "
    "task, what you just did, any irreversible step taken (so a restart never repeats "
    "it), blockers, and completed items as 'done_pending_verify' WITH evidence "
    "(links/counts/paths) for the curator to check. IMPORTANT: each tick starts with a "
    "CLEAN context — you do NOT remember previous ticks. Your memory across ticks is "
    "the board + DB + palace, so keep the file as an append-style, timestamped trail "
    "and reconstruct 'where am I' from it + the DB each tick, never from recall. NEVER "
    "write to a previous day's file — a still-open item in an old day's file means it "
    "was never finished; carry it forward via state/backlog.md or today's plan file "
    "instead. This is a standalone HTML document: follow state/progress/README.md and "
    "knowledge/reference/user_facing_html_artifacts.md (enterprise settings chrome — "
    "preserve the canonical style shell), preserve its doctype/head/styles and every "
    "existing entry, insert semantic content without scripts/forms/external assets, "
    "and leave valid DOM after every write.\n\n"
    "OUTPUT (this is the ONLY thing the user may see):\n"
    "  - If a state transition happened (started a long task / blocked / completed / "
    "failed), write a short one-line notification for the user. Otherwise output NO "
    "prose at all.\n"
    "  - ALWAYS end your turn with exactly one machine tag on its own line:\n"
    "      <<WORKER_STATUS: worked>>   if you did work and more may remain\n"
    "      <<WORKER_STATUS: idle>>     if nothing was actionable (or paused)"
)

WORKER_CLOCK_SUFFIX = (
    "\n\n[WORKER:CLOCK]\n"
    "NOW = <YYYY-MM-DD HH:MM> <agent timezone> (weekday <Day>)\n"
    "session_elapsed = <elapsed since worker started>\n"
    "project_slice_cap = 30m (if you have spent longer than this on one project, "
    "checkpoint and re-scan)\n"
    "today_progress_file = state/progress/<today>.html\n"
    "today_plan_file = state/plan/<today>.html"
)


def morning_prompt(today: str) -> str:
    return (
        "[SYSTEM:MORNING_ROUTINE] Good morning! It is a new workday. "
        "Please give a warm morning greeting. Then:\n"
        "1. Check for any calendar or planning items the user may need to respond to today.\n"
        "3. Note anything else relevant from overnight.\n"
        "4. If a `jobs/` board exists, plan today's work: set `state/worker_control.md` "
        "to `paused`, then read `state/steering.md` (fold the reflection's corrections "
        "in so the worker doesn't repeat past mistakes; your goals + recurring rules are "
        "already in your system prompt via config/JOBS.md, no need to read it), "
        "`state/backlog.md`, and the most recent prior day's file in `state/progress/` "
        "(list the directory to find it) for carry-forward items left after last "
        "night's rollover. If that file looks stale, reconcile it against "
        "the DB (exact counts, the authority) + last night's palace recap "
        "(`palace_search` for topic `daily-recap` / room=episodes) before "
        "carrying state forward — the plan must reflect what truly happened. Refresh the "
        "board: regenerate today's due rituals, carry forward unfinished projects "
        "(merge, never wipe in-progress state), then set `state/worker_control.md` back "
        "to `active`.\n"
        f"5. Record today's plan by write_file-ing `state/plan/{today}.html` — a NEW "
        "standalone HTML document (one per day; never touch or overwrite a previous "
        "day's file) briefing today's due rituals and carried-forward projects. Follow "
        "`state/plan/README.md` and "
        "`knowledge/reference/user_facing_html_artifacts.md` (copy the canonical "
        "enterprise settings style shell; no scripts, forms, or external dependencies). "
        "If it already exists (e.g. you're re-running today's planning), read_file it "
        "first, preserve the document shell/styles and prior content, and amend the "
        "valid DOM rather than clobbering it.\n"
        "Keep it concise but thorough. This also serves as a healthcheck."
    )


def catchup_prompt(today: str) -> str:
    return (
        "[SYSTEM:CATCHUP] You just came back online and the morning planning slot "
        "(09:10 agent timezone) was missed while the process was down or busy — today's plan was "
        "never set up. Run it now and reconcile what slipped:\n"
        f"- read_file `state/plan/{today}.html` (was today's plan ever written? a "
        f"missing file means no) and `state/progress/{today}.html` (what actually got "
        "done today so far, if anything) to see where the day stands.\n"
        "- Identify anything that was supposed to happen today but hasn't yet — morning "
        "planning never ran, a launched task left mid-flight, a due ritual not yet set "
        "up on the board — and surface those pending items to the user in your reply.\n"
        "- Rituals are 'do today's once': a slot missed earlier today is satisfied by "
        "doing it now, not repeated; projects carry forward until done.\n"
        "Then do today's morning planning:\n\n"
    ) + morning_prompt(today)


def reflection_prompt(today: str, memory_pass: bool = True) -> str:
    """`memory_pass=False` (every slot after the day's first) swaps the memory
    half for a skip note: the evidence bins move in days, so later slots
    re-reading the same rows spend the turn re-litigating the morning's
    judgments. The worker audit (PART 3) runs every slot regardless."""
    header = (
        "[SYSTEM:REFLECTION] This is an ambient reflection + periodic memory "
        "consolidation + worker-audit tick — consolidate memory, steer the "
        "background worker, and report a short status. You WILL end the turn "
        "with a brief plain summary to the user (see PART 3) — that summary "
        "is delivered to them, so make it tight and useful rather than trying "
        "to force an empty turn.\n\n"
    )
    memory_parts = (
        "PART 1 — Periodic memory consolidation. This is CROSS-EPISODE work "
        "only: you are not here to notice and file new one-off facts — the "
        "runtime `learn` tool and the task-end consolidator that already runs "
        "after every episode cover that. Your job is patterns and evidence "
        "visible only across MANY episodes: merge, strengthen, weaken, "
        "promote, archive, tune. Do not free-form infer lessons from raw "
        "conversation re-reading — that is exactly the memory-pollution "
        "failure mode this pass exists to avoid. Ground every action in one "
        "of the three sources below, not in a hunch.\n"
        "  1. Call memory_utility_report() first. It returns three "
        "harness-computed evidence bins from real retrieval telemetry — "
        "verify the actual content before acting on any row; the report "
        "gives you counts/ratios, never content:\n"
        "     - BAD-TRIGGER (graded often, rarely used, and the rare uses "
        "were NOT harmful): the content is fine, the cue surfacing it is too "
        "broad. Fix the trigger, never the content. If the memory_key has a "
        "backing recall, get_recall it and trim positives/lexical, add "
        "negative_examples, or raise positive_threshold via learn_recall "
        "(full array replace — mechanics in PART 2). A bare `drawer_search:"
        "<room>` or `kg:...` telemetry key with no recall pointing at it "
        "can't be re-cued this way — palace_search/kg_query rank by "
        "embedding/exact-match, not a tunable trigger; there may be nothing "
        "to fix beyond noting it.\n"
        "     - BAD-MEMORY (harmful use and/or a user correction): the "
        "content itself is wrong. Investigate with palace_search / "
        "palace_kg_query / palace_kg_timeline, then correct — for a KG fact: "
        "propose_memory(type=semantic, kg_invalidate=[the stale triple], "
        "kg_triplets=[the replacement]) — one call retires the old fact and "
        "files the new one, history preserved. For a drawer/procedure/"
        "preference: propose_memory "
        "with the corrected version, passing supersedes_memory_id=<the "
        "memory_id from the report row> when the old rule genuinely stopped "
        "applying. That records the replacement, so the retired rule keeps "
        "its place in the history and stops being surfaced as current. Use it "
        "only for a real replacement — a memory restating what another "
        "already says is reinforcement, and propose_memory's own dedupe "
        "handles that.\n"
        "     - STALE (graded before, nothing useful in 90+ days): reassess "
        "relevance rather than acting automatically. Still true but just "
        "under-triggered is actually a bad-trigger case — strengthen its cue "
        "coverage (add the phrasings that SHOULD have retrieved it to the "
        "pointing recall's positive_examples) instead of leaving it to rot. "
        "Genuinely obsolete: propose_memory(type=semantic, kg_invalidate=[the "
        "triple]) for a KG fact, or "
        "purge_recall for a clearly-dead USER recall (never a sys_* recall). "
        "When truly unsure, leave it — staleness is a prompt to look, not an "
        "automatic delete.\n"
        "  2. Cross-episode duplicates the automatic pipeline can't see: "
        "commit-time dedupe only catches IDENTICAL text among the last ~200 "
        "candidates from the last 30 days of the SAME type (see "
        "harness/consolidation.py _is_prose_duplicate); reworded restatements "
        "are recorded by the edge classifier but still written. Spot-check a "
        "topic you suspect has "
        "drifted with palace_search / palace_kg_query; merge any true "
        "duplicates or contradictions you find the same way as a BAD-MEMORY "
        "fix above.\n"
        "  3. Repeated patterns worth promoting to procedure: if "
        "palace_search (room=procedures, room=knowledge, or "
        "knowledge/procedures/) shows the SAME lesson filed independently "
        "more than once by task-end consolidation passes, that repetition IS "
        "the cross-episode evidence this pass exists to catch — write ONE "
        "clean canonical version via propose_memory(type=procedural), noting "
        "in it which near-duplicates it consolidates (they can stay on disk; "
        "there is no delete, but the canonical entry is now the one to "
        "trust and knowledge/INDEX.md should point at it).\n"
        "Also, unrelated to memory (a separate adaptive-state system, "
        "unchanged by the above): read "
        "knowledge/skills/experiential-reflection.md and use "
        "experience_report for an independent metacognitive appraisal of the "
        "shared state. When an outcome forms a durable experiential episode, "
        "file its event, prior state, state change, decision, consequence, "
        "and lesson via propose_memory(type=episodic) — it lands in "
        "room=episodes with no recall trigger, which is right for a record.\n\n"
        "PART 2 — Recall-cue tuning mechanics. This is the tool surface for "
        "PART 1's bad-trigger/stale fixes, not a separate audit — auditing "
        "individual fires now happens every episode in task-end "
        "consolidation; this pass only acts once evidence has accumulated "
        "across many of them. Two-stage pipeline (cue/threshold patches "
        "retune Stage-1+2): Stage-1 is a positive-only proposer (per-recall "
        "positive_threshold + lexical cues; chunks under 4 words are "
        "lexical-only) → Stage-2 is an LLM entailment judge reading the "
        "recall's `activation_condition` and `exclusions` against "
        "`matched_chunk`, plus a junk filter for bare tools/HTML → "
        "only verified fires inject as a recall() tool exchange. Defaults: "
        "positive_threshold=0.6; negatives NEVER gate Stage-1 — they reach "
        "Stage-2 as few-shot known-misfire vetoes, so a negative only helps "
        "when it reads like a case the judge should refuse. Always "
        "get_recall for the complete current arrays before any patch — "
        "learn_recall arrays are FULL replacements, never a partial append.\n"
        "Cue quality (bad cues waste every future turn):\n"
        "  - positive_examples: realistic phrasings that should fire (NOT "
        "paraphrases of the instruction) — dense coverage helps, up to ~100.\n"
        "  - lexical_cues: high-precision exact anchors that should hard-hit.\n"
        "  - negative_examples: known misfires (Stage-2 counter-signal only; "
        "never gates Stage-1).\n"
        "  - positive_threshold: 0–1 Stage-1 positive floor (default 0.6), "
        "visible on get_recall — raise it when trimming cues alone doesn't "
        "fix a bad trigger; lower it slightly when strengthening an "
        "under-triggered good memory.\n"
        "Prefer patching an existing recall over creating a new one for the "
        "same rule. `purge_recall` only for genuinely dead USER recalls — "
        "system (`sys_*`) recall instructions are immutable; only their cue "
        "arrays and thresholds are yours to tune. Do not essay facts into an "
        "instruction field — an instruction is a pointer to a store, not the "
        "store itself.\n\n"
    )
    memory_skipped = (
        "PART 1 & 2 — SKIPPED THIS SLOT. Memory consolidation ran on an "
        "earlier slot today, and its evidence (utility bins, staleness, "
        "cross-episode duplicates) moves in days, not hours — do NOT call "
        "memory_utility_report or tune recall cues now; re-judging the same "
        "rows re-litigates this morning's decisions. One exception: if "
        "TODAY'S conversation contains an explicit user correction of stored "
        "memory, flag_memory / propose_memory for that single item is still "
        "in scope. Your job this slot is PART 3.\n\n"
    )
    part3 = (
        "PART 3 — Audit the worker, reconcile the ledger, steer, and SUMMARIZE. "
        f"Read today's file `state/progress/{today}.html` (if it exists) and the "
        "recent linkedin_profiles DB writes; compare what the worker ACTUALLY did "
        "against the active cookbook(s) in jobs/ and config/GUARDRAILS.md. Also "
        "reconcile the CURATOR: did you take real actions in conversation today "
        "(sends, completions, DB flips) that are NOT reflected in that file? You "
        "are ONE agent — chat work counts. If the shared ledger is missing or "
        f"contradicts what actually happened, write_file `state/progress/{today}.html` "
        "(and the DB if needed) so goodnight/morning can't contradict the evening. "
        "For every HTML update, read immediately before writing, preserve the complete "
        "document shell/styles (enterprise settings chrome from "
        "knowledge/reference/user_facing_html_artifacts.md) and all prior entries, "
        "and leave valid DOM. "
        "Then:\n"
        "  - If there's a correction worth carrying forward (any drift, even "
        "minor), APPEND a dated, descriptive note to state/steering.md (read_file "
        "first, then write_file old content with your new entry on TOP — never "
        "wipe history), concrete enough that a fresh worker tick (no memory of "
        "past ticks) won't repeat the mistake. Skip the write only if there is "
        "genuinely nothing to add. If this steering changes today's plan, also "
        f"amend today's file `state/plan/{today}.html` with a timestamped entry noting "
        "the change (read_file first, then write_file — never touch other days' "
        "files) — the planning ledger should reflect any re-planning.\n"
        "  - If the worker is doing something BAD/unwanted, or is consistently "
        "misbehaving / not doing the job: also PAUSE it — write_file "
        "state/worker_control.md with `paused` as the first line (it finishes its "
        "current unit, then stops).\n"
        "  - ALWAYS end the turn with the status summary for the user — a few "
        "lines, scalpel-brief. Lead with the headline (ALL GOOD / STEERED / "
        "PAUSED), then a line or two on what the worker has been doing, whether "
        "the cookbooks, guardrails and voice all look respected, and any "
        "correction you filed or action you took. A short honest status every "
        "tick is the goal — don't try to stay silent."
    )
    return header + (memory_parts if memory_pass else memory_skipped) + part3


def goodnight_prompt(today: str) -> str:
    return (
        "[SYSTEM:GOODNIGHT_ROUTINE] It is goodnight time in the agent timezone. Wish the user a peaceful "
        "good night, with a brief reflection if the day had anything notable.\n"
        "First, reconcile the day to ONE truth — you are ONE agent and this is "
        f"a fresh channel, so `state/progress/{today}.html` alone is NOT the whole "
        "story. Cross-check it against the DB (exact counts, the authority) and "
        "what you actually did in chat today (`palace_search` room=conversations "
        "/ today's daily log) and last night's operational narrative "
        "(`palace_search` room=episodes). If something you sent or finished isn't in that "
        "file, the ledger is stale — trust the DB + what actually happened, "
        "fix the file (read_file then write_file — never touch a previous day's "
        "file), and report THAT. If background jobs ran, verify the evidence on "
        "any `done_pending_verify` items before calling them done, and flag "
        "anything still open or blocked for tomorrow.\n"
        "Then file today's recap to memory — "
        "`learn(type=\"episodic\", topic=\"daily-recap\", content=...)`, with the "
        f"content starting with the date ({today}) and covering what got done, "
        "what is open, and anything surprising (this is where "
        f"tomorrow recalls what got done today). Leave `state/progress/{today}.html` "
        "as-is otherwise (it is the permanent record of today, one file per day — "
        "never trim or wipe it); still-open/carry-forward items simply stay in it "
        "as unfinished lines, and tomorrow's morning planning will pick them up by "
        "reading this file.\n"
        "After this message you "
        "enter REST — your heartbeat is disabled until morning."
    )


def process_complete_prompt(data: dict) -> str:
    return (
        "[SYSTEM:PROCESS_COMPLETE] A background shell process has finished.\n\n"
        f"Process: {data.get('job', 'unknown')}\n"
        f"Status: {data.get('status', 'UNKNOWN')}\n"
        f"Details:\n```json\n{json.dumps(data, indent=2)}\n```\n\n"
        "Notify the user about this. Include the key stats. "
        "If it succeeded, celebrate briefly and suggest next steps. "
        "If it failed, analyze what might have gone wrong and suggest a fix. "
        "Keep it concise."
    )


PROCESS_COMPLETE_EXAMPLE = process_complete_prompt(
    {
        "job": "example_narration",
        "status": "SUCCESS",
        "exit_code": 0,
        "elapsed_seconds": 142,
        "log_file": "logs/example.done",
        "completed_at": "2026-07-03T21:00:00",
    }
)


def task_consolidation_prompt() -> str:
    """Task-end memory consolidation — one agent turn per finished episode, on
    a disposable side channel (see GaladrielAgent.run_task_consolidation).
    Never shown to the user. Absorbs what the old recall-fire audit did
    (folded into the recall-cue-tuning section below) plus the full scope
    from the multi-timescale learning plan: missed learnings, corrections,
    strategy outcomes, and retrieval grading — see harness/consolidation.py
    for how every tool call here turns into a deterministic write/counter.
    """
    return (
        "[SYSTEM:TASK_CONSOLIDATION] Silent memory-consolidation pass for the "
        "episode that just ended — not shown to the user. This is the pass "
        "responsible for turning the episode into durable memory with the "
        "benefit of hindsight over the whole thing; a conservative `learn` "
        "call may already have fired mid-episode for obvious cases, but most "
        "learning should happen here.\n\n"
        "Context provided below: the episode transcript (the live tail — see "
        "[EPISODE_INDEX] for the compaction summary chain and archived "
        "segment ids covering anything already folded out of it), the "
        "current recall catalog, an [EPISODE_RETRIEVALS] list of memory "
        "surfaced during the episode, and a [RECENT_CONSOLIDATION_DIGEST] of "
        "what recent passes already decided — don't repeat those.\n\n"
        "Your tools:\n"
        "  - propose_memory(type, content|kg_triplets, topic, "
        "evidence_episode_ids, confidence, note) — the ONLY way to write new "
        "memory from this pass. Harness code validates, dedupes, and commits "
        "it; you only express judgment about what's worth keeping.\n"
        "  - grade_retrieval(retrieval_id, used, outcome, note) — call once "
        "for EVERY id listed in [EPISODE_RETRIEVALS]. used=false means "
        "retrieved but ignored. used=true + outcome=helpful/harmful means it "
        "influenced behavior and that went well or badly. This is what lets "
        "later passes tell a bad memory apart from a memory with a "
        "too-broad trigger — a memory that fires constantly but is rarely "
        "used, and helpful on the rare uses, needs a narrower cue, not new "
        "content; a memory that gets used and goes badly, or gets corrected, "
        "needs rewriting.\n"
        "  - flag_memory(memory_key, reason) — the user contradicted or "
        "corrected an existing memory this episode, whether or not it was "
        "retrieved. Strongest single signal for a later rewrite.\n"
        "  - read_episode_segment(segment_id) — verbatim drill-down into one "
        "archived compaction chunk listed in [EPISODE_INDEX]. Use "
        "selectively: pull a segment only when its summary hints at "
        "something learnable (a correction, a failure, a strategy change). "
        "Most segments don't need this — cost should track what looks "
        "learnable, not episode length. If a segment id is unreadable on this "
        "host, the same verbatim history is in the palace: palace_search it "
        "with room=conversations.\n"
        "  - Read-only lookups: palace_search, palace_kg_query, "
        "palace_kg_timeline, get_recall, get_recent_recalls — check for "
        "existing or contradicting memory before proposing.\n"
        "  - Recall-cue tuning (same two-stage pipeline as always: Stage-1 "
        "positive_threshold + lexical cues propose, Stage-2 an LLM "
        "entailment judge on activation_condition/exclusions verifies): "
        "learn_recall, "
        "tune_recall, purge_recall. This tunes WHEN a memory should "
        "resurface, not what it says — content problems are a "
        "propose_memory/flag_memory concern. For a fire in "
        "[RECALL_FIRES_IN_BUFFER] that was the wrong intent: "
        "tune_recall(recall_id, applicable=false) or get_recall → trim/"
        "raise threshold → learn_recall (full array replace). For a miss "
        "that should have fired: strengthen positives/lexical the same way.\n\n"
        "What to look for, roughly in order of value:\n"
        "1. MISSED LEARNING — the highest-value case, and the one a "
        "mid-episode `learn` call typically can't catch: a correction "
        "followed by a behavior change that then worked (user says 'no, use "
        "method B', agent switches, it succeeds). That is strong evidence "
        "for a procedural candidate even though nobody called `learn` in "
        "the moment.\n"
        "2. Explicit user corrections/contradictions of anything you "
        "already know -> flag_memory, plus propose_memory with the "
        "corrected version if you're confident what it should say instead. "
        "When the correction retires the old rule rather than refining it, "
        "add supersedes_memory_id=<the replaced memory_id> so the retired "
        "one stops being surfaced as current while staying in the record.\n"
        "3. A strategy that clearly failed or clearly succeeded in a way "
        "that would generalize beyond this one episode -> "
        "propose_memory(type=procedural).\n"
        "4. A durable fact about the user/project/entity that surfaced but "
        "was never explicitly filed -> propose_memory(type=semantic).\n"
        "5. A lasting behavioral preference the user expressed -> "
        "propose_memory(type=preference).\n"
        "6. Every retrieval_id in [EPISODE_RETRIEVALS] NOT marked [already "
        "graded] -> exactly one grade_retrieval call — this step is not "
        "optional. Judge used and helpful/harmful from what the episode "
        "actually did; don't default to used=false. [not opened] is harness "
        "context, not a verdict: a recall whose instruction you followed "
        "directly is used=true even though its memory was never opened.\n\n"
        "Be conservative on propose_memory: a one-off detail that won't "
        "recur isn't worth writing (duplicates are auto-skipped but still "
        "cost a review). Cross-episode pattern-finding (merging, decay, "
        "promoting repeated episodes into procedures) is deliberately NOT "
        "this pass's job — that's the periodic consolidator's scope, done "
        "with evidence across many episodes, not guessed from one. An empty "
        "turn (no tool calls beyond the required grade_retrieval ones) is "
        "the normal, expected outcome when nothing new happened. Act via "
        "tools only — no prose commentary."
    )
